# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
import random
from PyQt5 import QtCore, QtGui, QtWidgets

low = 1
high = 6


def dice_roll(low, high):
    player_roll = random.randint(low, high)
    return player_roll
    # exit()


def computer_roll(low, high):
    computer_result = random.randint(low, high)
    return computer_result


def roll_the_dice():
    ui.text_box.setText('You roll the dice...')
    time.sleep(1)
    computer_result = computer_roll(low, high)
    player_roll = dice_roll(low, high)
    if player_roll == computer_result:
        ui.text_box.append('Tie')
    elif player_roll > computer_result:
        ui.text_box.append('You Won!')
    else:
        ui.text_box.append('You lose...')
    print(f'your roll was {player_roll}')
    print(f'the computers roll was {computer_result}')
    ui.text_box.append(
        f'your roll was {player_roll} \nthe computers roll was {computer_result}')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dice_button = QtWidgets.QPushButton(self.centralwidget)
        self.dice_button.setGeometry(QtCore.QRect(150, 70, 521, 131))
        self.dice_button.setObjectName("dice_button")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(320, 260, 111, 71))
        self.result_label.setObjectName("result_label")
        self.text_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_box.setGeometry(QtCore.QRect(250, 340, 256, 192))
        self.text_box.setObjectName("text_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # this is all custom stuff
        self.text_box.setReadOnly(False)
        self.dice_button.clicked.connect(roll_the_dice)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dice_button.setText(_translate("MainWindow", "ROLL DA DICE"))
        self.result_label.setText(_translate("MainWindow", "Result"))


stylesheet = """
        #MainWindow {
            background-image: url("./background.jpg");
            background-size: cover;
            background-position: center;
        }
        """

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(stylesheet)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
